name: ngx-translate
description: Automates generation of translate maps for Angular apps using @ngx-translate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-translations:
    name: Generate translations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '281.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Translate
        run: node index.js
